/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddressDto {

  /**
   * City
   */
  city?: string;

  /**
   * State
   */
  state?: string;

  /**
   * Street address
   */
  street?: string;

  /**
   * ZIP code
   */
  zip?: string;
}
