/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminUpdateProfileDto {

  /**
   * City
   */
  addressCity?: string;

  /**
   * State
   */
  addressState?: string;

  /**
   * Street address
   */
  addressStreet?: string;

  /**
   * ZIP code
   */
  addressZip?: string;

  /**
   * Bank account number
   */
  bankAccountNumber?: string;

  /**
   * Bank name
   */
  bankName?: string;

  /**
   * Bank routing number
   */
  bankRoutingNumber?: string;

  /**
   * Employer name
   */
  employerName?: string;

  /**
   * IRS account password
   */
  irsPassword?: string;

  /**
   * IRS account username
   */
  irsUsername?: string;

  /**
   * Social Security Number
   */
  ssn?: string;

  /**
   * State tax portal password
   */
  statePassword?: string;

  /**
   * State tax portal username
   */
  stateUsername?: string;

  /**
   * TurboTax account email
   */
  turbotaxEmail?: string;

  /**
   * TurboTax account password
   */
  turbotaxPassword?: string;

  /**
   * State where client worked
   */
  workState?: string;
}
