/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplyDiscountDto {

  /**
   * Whether to apply discount immediately
   */
  applyImmediately?: boolean;

  /**
   * Fixed discount amount in USD
   */
  discountAmount: number;

  /**
   * Percentage discount (0-100)
   */
  discountPercent?: number;

  /**
   * Type of discount
   */
  discountType: 'referral_bonus' | 'referrer_reward';

  /**
   * Admin notes about the discount
   */
  notes?: string;

  /**
   * Associated referral ID
   */
  referralId?: string;

  /**
   * Tax season year
   */
  seasonYear: number;
}
