/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthUserDto {

  /**
   * User email
   */
  email: string;

  /**
   * User first name
   */
  firstName?: string;

  /**
   * User ID
   */
  id: string;

  /**
   * Whether email is verified
   */
  isEmailVerified?: boolean;

  /**
   * Whether profile is complete
   */
  isProfileComplete?: boolean;

  /**
   * User last name
   */
  lastName?: string;

  /**
   * User role
   */
  role: 'admin' | 'client';
}
