/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthUserDto } from '../models/auth-user-dto';
export interface AuthResponseDto {

  /**
   * JWT access token
   */
  access_token: string;

  /**
   * Access token expiry time in seconds
   */
  expires_in: number;

  /**
   * Refresh token for obtaining new access tokens
   */
  refresh_token: string;

  /**
   * User information
   */
  user?: AuthUserDto;
}
