/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BankDto {

  /**
   * Bank account number
   */
  account_number?: string;

  /**
   * Bank name
   */
  name?: string;

  /**
   * Bank routing number (9 digits)
   */
  routing_number?: string;
}
