/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChangePasswordDto {

  /**
   * Current password for verification
   */
  current_password: string;

  /**
   * New password (min 8 characters)
   */
  new_password: string;
}
