/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AddressDto } from '../models/address-dto';
import { BankDto } from '../models/bank-dto';
export interface CompleteProfileDto {

  /**
   * Mailing address
   */
  address?: AddressDto;

  /**
   * Bank account information
   */
  bank?: BankDto;

  /**
   * Date of birth (ISO 8601)
   */
  date_of_birth?: string;

  /**
   * Employer name
   */
  employer_name?: string;

  /**
   * Whether this is a draft save (allows partial data)
   */
  is_draft?: boolean;

  /**
   * Payment method
   */
  payment_method?: 'bank_deposit' | 'check';

  /**
   * Phone number in E.164 format
   */
  phone?: string;

  /**
   * Social Security Number (9 digits, with or without dashes)
   */
  ssn?: string;

  /**
   * TurboTax account email
   */
  turbotax_email?: string;

  /**
   * TurboTax account password
   */
  turbotax_password?: string;

  /**
   * State where client worked
   */
  work_state?: string;
}
