/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTicketDto {

  /**
   * Initial message for the ticket
   */
  message?: string;

  /**
   * Ticket subject/title
   */
  subject: string;
}
