/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTicketResponseDto {

  /**
   * Created ticket ID
   */
  id: string;

  /**
   * Success message
   */
  message: string;

  /**
   * Ticket status
   */
  status: string;

  /**
   * Ticket subject
   */
  subject: string;
}
