/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageSenderDto {

  /**
   * Sender first name
   */
  firstName?: string;

  /**
   * Sender ID
   */
  id: string;

  /**
   * Sender last name
   */
  lastName?: string;

  /**
   * Sender role
   */
  role: 'admin' | 'client';
}
