/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationActionResponseDto {

  /**
   * Number of affected notifications
   */
  count?: number;

  /**
   * Success status
   */
  success: boolean;
}
