/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NotificationDto } from '../models/notification-dto';
export interface NotificationsPaginatedResponseDto {

  /**
   * Whether more results exist
   */
  hasMore: boolean;

  /**
   * Cursor for next page
   */
  nextCursor?: {
} | null;

  /**
   * List of notifications
   */
  notifications: Array<NotificationDto>;
}
