/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationDto {

  /**
   * Creation timestamp
   */
  createdAt: string;

  /**
   * Notification ID
   */
  id: string;

  /**
   * Whether notification is archived
   */
  isArchived: boolean;

  /**
   * Whether notification has been read
   */
  isRead: boolean;

  /**
   * Notification message
   */
  message: string;

  /**
   * Notification title
   */
  title: string;

  /**
   * Notification type
   */
  type: 'status_update' | 'document_update' | 'message' | 'refund_update' | 'referral' | 'system';

  /**
   * User ID who received the notification
   */
  userId: string;
}
