/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RefreshTokenDto {

  /**
   * Refresh token for obtaining new access tokens
   */
  refresh_token: string;
}
