/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterDto {

  /**
   * User email address
   */
  email: string;

  /**
   * User first name
   */
  first_name: string;

  /**
   * User last name
   */
  last_name: string;

  /**
   * User password (min 8 chars, must include uppercase, lowercase, number, and special char)
   */
  password: string;

  /**
   * User phone number
   */
  phone?: string;

  /**
   * Referral code from another user
   */
  referral_code?: string;
}
