/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthUserDto } from '../models/auth-user-dto';
export interface RegisterResponseDto {

  /**
   * Success message
   */
  message: string;

  /**
   * User information
   */
  user: AuthUserDto;

  /**
   * Whether verification email was sent
   */
  verificationEmailSent?: boolean;
}
