/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResetPasswordDto {

  /**
   * New password (min 8 characters)
   */
  new_password: string;

  /**
   * Password reset token from email
   */
  token: string;
}
