/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SendNotificationDto {

  /**
   * Notification message content
   */
  message: string;

  /**
   * Whether to also send email notification
   */
  sendEmail?: boolean;

  /**
   * Notification title
   */
  title: string;
}
