/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SetProblemDto {

  /**
   * Whether client has a problem
   */
  hasProblem: boolean;

  /**
   * Detailed description of the problem
   */
  problemDescription?: string;

  /**
   * Type of problem (required if hasProblem=true)
   */
  problemType?: string;
}
