/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SetThresholdsDto {

  /**
   * Disable federal status alarms
   */
  disableFederalAlarms?: boolean;

  /**
   * Disable state status alarms
   */
  disableStateAlarms?: boolean;

  /**
   * Days before federal in-process status triggers alarm (1-365)
   */
  federalInProcessDays?: {
};

  /**
   * Days before letter sent timeout triggers alarm (1-365)
   */
  letterSentTimeoutDays?: {
};

  /**
   * Reason for threshold change (for audit log)
   */
  reason?: string;

  /**
   * Days before state in-process status triggers alarm (1-365)
   */
  stateInProcessDays?: {
};

  /**
   * Days before verification timeout triggers alarm (1-365)
   */
  verificationTimeoutDays?: {
};
}
