/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TicketListItemDto } from '../models/ticket-list-item-dto';
export interface TicketsPaginatedResponseDto {

  /**
   * Whether more results exist
   */
  hasMore: boolean;

  /**
   * Cursor for next page
   */
  nextCursor?: {
} | null;

  /**
   * List of tickets
   */
  tickets: Array<TicketListItemDto>;
}
