/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MessageSenderDto } from '../models/message-sender-dto';
export interface TicketMessageDto {

  /**
   * Message creation timestamp
   */
  createdAt: string;

  /**
   * Message ID
   */
  id: string;

  /**
   * Whether message has been read
   */
  isRead: boolean;

  /**
   * Message content
   */
  message: string;

  /**
   * Sender information
   */
  sender: MessageSenderDto;

  /**
   * Sender ID
   */
  senderId: string;
}
