/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TicketUserDto {

  /**
   * User email
   */
  email: string;

  /**
   * User first name
   */
  firstName?: string;

  /**
   * User ID
   */
  id: string;

  /**
   * User last name
   */
  lastName?: string;

  /**
   * User role
   */
  role?: 'admin' | 'client';
}
