/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TicketMessageDto } from '../models/ticket-message-dto';
import { TicketUserDto } from '../models/ticket-user-dto';
export interface TicketDetailDto {

  /**
   * Creation timestamp
   */
  createdAt: string;

  /**
   * Ticket ID
   */
  id: string;

  /**
   * Ticket messages
   */
  messages: Array<TicketMessageDto>;

  /**
   * Ticket status
   */
  status: 'open' | 'in_progress' | 'closed';

  /**
   * Ticket subject
   */
  subject: string;

  /**
   * Number of unread messages
   */
  unreadCount: number;

  /**
   * Last update timestamp
   */
  updatedAt: string;

  /**
   * User information
   */
  user: TicketUserDto;

  /**
   * Owner user ID
   */
  userId: string;
}
