/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateReferralStatusDto {

  /**
   * New referral status
   */
  status: 'pending' | 'tax_form_submitted' | 'awaiting_refund' | 'successful' | 'expired';
}
