/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateSensitiveProfileDto {

  /**
   * Bank account number
   */
  bankAccountNumber?: string;

  /**
   * Bank name
   */
  bankName?: string;

  /**
   * Bank routing number (9 digits)
   */
  bankRoutingNumber?: string;

  /**
   * Social Security Number (9 digits)
   */
  ssn?: string;

  /**
   * TurboTax account email
   */
  turbotaxEmail?: string;

  /**
   * TurboTax account password
   */
  turbotaxPassword?: string;
}
