/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTicketStatusResponseDto {

  /**
   * Ticket ID
   */
  id: string;

  /**
   * Success message
   */
  message: string;

  /**
   * Updated status
   */
  status: string;
}
