/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UploadDocumentDto {

  /**
   * Tax year for the document
   */
  tax_year?: number;

  /**
   * Document type
   */
  type: 'w2' | 'payment_proof' | 'other';
}
