/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ProgressControllerCheckMissingDocuments$Params {
  daysThreshold: string;
  maxNotifications: string;
}

export function progressControllerCheckMissingDocuments(http: HttpClient, rootUrl: string, params: ProgressControllerCheckMissingDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, progressControllerCheckMissingDocuments.PATH, 'post');
  if (params) {
    rb.query('daysThreshold', params.daysThreshold, {});
    rb.query('maxNotifications', params.maxNotifications, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

progressControllerCheckMissingDocuments.PATH = '/v1/admin/progress/check-missing-documents';
