/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationActionResponseDto } from '../../models/notification-action-response-dto';

export interface NotificationsControllerArchiveAllRead$Params {
}

export function notificationsControllerArchiveAllRead(http: HttpClient, rootUrl: string, params?: NotificationsControllerArchiveAllRead$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationActionResponseDto>> {
  const rb = new RequestBuilder(rootUrl, notificationsControllerArchiveAllRead.PATH, 'patch');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationActionResponseDto>;
    })
  );
}

notificationsControllerArchiveAllRead.PATH = '/v1/notifications/archive-all-read';
