/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationActionResponseDto } from '../../models/notification-action-response-dto';

export interface NotificationsControllerMarkAllAsRead$Params {
}

export function notificationsControllerMarkAllAsRead(http: HttpClient, rootUrl: string, params?: NotificationsControllerMarkAllAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationActionResponseDto>> {
  const rb = new RequestBuilder(rootUrl, notificationsControllerMarkAllAsRead.PATH, 'patch');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationActionResponseDto>;
    })
  );
}

notificationsControllerMarkAllAsRead.PATH = '/v1/notifications/read-all';
