/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationsPaginatedResponseDto } from '../../models/notifications-paginated-response-dto';

export interface NotificationsControllerFindAll$Params {

/**
 * Filter to only unread
 */
  unreadOnly?: string;

/**
 * Include archived notifications
 */
  includeArchived?: string;

/**
 * Pagination cursor
 */
  cursor?: string;

/**
 * Items per page
 */
  limit?: string;
}

export function notificationsControllerFindAll(http: HttpClient, rootUrl: string, params?: NotificationsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationsPaginatedResponseDto>> {
  const rb = new RequestBuilder(rootUrl, notificationsControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('unreadOnly', params.unreadOnly, {});
    rb.query('includeArchived', params.includeArchived, {});
    rb.query('cursor', params.cursor, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationsPaginatedResponseDto>;
    })
  );
}

notificationsControllerFindAll.PATH = '/v1/notifications';
