/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UnreadCountResponseDto } from '../../models/unread-count-response-dto';

export interface NotificationsControllerGetUnreadCount$Params {
}

export function notificationsControllerGetUnreadCount(http: HttpClient, rootUrl: string, params?: NotificationsControllerGetUnreadCount$Params, context?: HttpContext): Observable<StrictHttpResponse<UnreadCountResponseDto>> {
  const rb = new RequestBuilder(rootUrl, notificationsControllerGetUnreadCount.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UnreadCountResponseDto>;
    })
  );
}

notificationsControllerGetUnreadCount.PATH = '/v1/notifications/unread-count';
