/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TicketDetailDto } from '../../models/ticket-detail-dto';

export interface TicketsControllerFindOne$Params {
  id: string;
}

export function ticketsControllerFindOne(http: HttpClient, rootUrl: string, params: TicketsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<TicketDetailDto>> {
  const rb = new RequestBuilder(rootUrl, ticketsControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TicketDetailDto>;
    })
  );
}

ticketsControllerFindOne.PATH = '/v1/tickets/{id}';
