/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTicketDto } from '../../models/create-ticket-dto';
import { CreateTicketResponseDto } from '../../models/create-ticket-response-dto';

export interface TicketsControllerCreate$Params {
      body: CreateTicketDto
}

export function ticketsControllerCreate(http: HttpClient, rootUrl: string, params: TicketsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<CreateTicketResponseDto>> {
  const rb = new RequestBuilder(rootUrl, ticketsControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreateTicketResponseDto>;
    })
  );
}

ticketsControllerCreate.PATH = '/v1/tickets';
