/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateStatusDto } from '../../models/update-status-dto';
import { UpdateTicketStatusResponseDto } from '../../models/update-ticket-status-response-dto';

export interface TicketsControllerUpdateStatus$Params {
  id: string;
      body: UpdateStatusDto
}

export function ticketsControllerUpdateStatus(http: HttpClient, rootUrl: string, params: TicketsControllerUpdateStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<UpdateTicketStatusResponseDto>> {
  const rb = new RequestBuilder(rootUrl, ticketsControllerUpdateStatus.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UpdateTicketStatusResponseDto>;
    })
  );
}

ticketsControllerUpdateStatus.PATH = '/v1/tickets/{id}/status';
