/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TicketsPaginatedResponseDto } from '../../models/tickets-paginated-response-dto';

export interface TicketsControllerFindAll$Params {
  status?: 'open' | 'in_progress' | 'closed';

/**
 * Filter by user ID (admin only)
 */
  user_id?: string;

/**
 * Pagination cursor
 */
  cursor?: string;

/**
 * Items per page
 */
  limit?: string;
}

export function ticketsControllerFindAll(http: HttpClient, rootUrl: string, params?: TicketsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<TicketsPaginatedResponseDto>> {
  const rb = new RequestBuilder(rootUrl, ticketsControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('user_id', params.user_id, {});
    rb.query('cursor', params.cursor, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TicketsPaginatedResponseDto>;
    })
  );
}

ticketsControllerFindAll.PATH = '/v1/tickets';
