/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ReferralsControllerGetAllReferrals$Params {
  status: string;
  search: string;
  limit: string;
  offset: string;
}

export function referralsControllerGetAllReferrals(http: HttpClient, rootUrl: string, params: ReferralsControllerGetAllReferrals$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, referralsControllerGetAllReferrals.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('search', params.search, {});
    rb.query('limit', params.limit, {});
    rb.query('offset', params.offset, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

referralsControllerGetAllReferrals.PATH = '/v1/referrals/admin';
