/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ReferralsControllerGetReferralSummary$Params {
  cursor: string;
  limit: string;
}

export function referralsControllerGetReferralSummary(http: HttpClient, rootUrl: string, params: ReferralsControllerGetReferralSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, referralsControllerGetReferralSummary.PATH, 'get');
  if (params) {
    rb.query('cursor', params.cursor, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

referralsControllerGetReferralSummary.PATH = '/v1/referrals/admin/summary';
