/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AlarmsControllerDeleteThresholds$Params {
  taxCaseId: string;
}

export function alarmsControllerDeleteThresholds(http: HttpClient, rootUrl: string, params: AlarmsControllerDeleteThresholds$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, alarmsControllerDeleteThresholds.PATH, 'delete');
  if (params) {
    rb.path('taxCaseId', params.taxCaseId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

alarmsControllerDeleteThresholds.PATH = '/v1/admin/alarms/thresholds/{taxCaseId}';
