/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AlarmsControllerGetHistory$Params {
  taxCaseId: string;
  alarmType: string;
  alarmLevel: string;
  resolution: string;
  track: string;
  fromDate: string;
  toDate: string;
}

export function alarmsControllerGetHistory(http: HttpClient, rootUrl: string, params: AlarmsControllerGetHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, alarmsControllerGetHistory.PATH, 'get');
  if (params) {
    rb.query('taxCaseId', params.taxCaseId, {});
    rb.query('alarmType', params.alarmType, {});
    rb.query('alarmLevel', params.alarmLevel, {});
    rb.query('resolution', params.resolution, {});
    rb.query('track', params.track, {});
    rb.query('fromDate', params.fromDate, {});
    rb.query('toDate', params.toDate, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

alarmsControllerGetHistory.PATH = '/v1/admin/alarms/history';
