/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AlarmsControllerResolveAlarm$Params {
  alarmId: string;
}

export function alarmsControllerResolveAlarm(http: HttpClient, rootUrl: string, params: AlarmsControllerResolveAlarm$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, alarmsControllerResolveAlarm.PATH, 'post');
  if (params) {
    rb.path('alarmId', params.alarmId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

alarmsControllerResolveAlarm.PATH = '/v1/admin/alarms/{alarmId}/resolve';
