/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SetThresholdsDto } from '../../models/set-thresholds-dto';

export interface AlarmsControllerSetThresholds$Params {
  taxCaseId: string;
      body: SetThresholdsDto
}

export function alarmsControllerSetThresholds(http: HttpClient, rootUrl: string, params: AlarmsControllerSetThresholds$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, alarmsControllerSetThresholds.PATH, 'patch');
  if (params) {
    rb.path('taxCaseId', params.taxCaseId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

alarmsControllerSetThresholds.PATH = '/v1/admin/alarms/thresholds/{taxCaseId}';
