/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ClientsControllerExportToExcel$Params {
  status: string;
  search: string;
  hasProblem: string;
  federalStatus: string;
  stateStatus: string;
  caseStatus: string;
  dateFrom: string;
  dateTo: string;
}

export function clientsControllerExportToExcel(http: HttpClient, rootUrl: string, params: ClientsControllerExportToExcel$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, clientsControllerExportToExcel.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('search', params.search, {});
    rb.query('hasProblem', params.hasProblem, {});
    rb.query('federalStatus', params.federalStatus, {});
    rb.query('stateStatus', params.stateStatus, {});
    rb.query('caseStatus', params.caseStatus, {});
    rb.query('dateFrom', params.dateFrom, {});
    rb.query('dateTo', params.dateTo, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

clientsControllerExportToExcel.PATH = '/v1/admin/clients/export';
